### ISSUE TITLE
CudNN failed to initialize when calling model_inspect.py

### ISSUE THREAD

**Issue by Cyril9227** [google/automl#33]
I get an obscur cudnn error when running `python3 model_inspect.py --runmode infer --model_name efficientdet-d1 --ckpt_path=path/to/efficientdet-d1 --input_imagepath/to/image.png  --output_image_dir path/to/outputdir`

My CUDA version is 10.1 and Tensorflow's is '2.1.0'

```
2020-03-24 07:35:36.937706: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-24 07:35:38.730679: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-03-24 07:35:38.733928: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node efficientnet-b1/model/stem/conv2d/Conv2D}}]]
	 [[strided_slice_10/_1837]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node efficientnet-b1/model/stem/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "model_inspect.py", line 333, in <module>
    tf.app.run(main)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 328, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 306, in run_model
    **config_dict)
  File "model_inspect.py", line 186, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/home/jupyter-cyril/git_projects/automl/efficientdet/inference.py", line 289, in inference
    outputs_np = sess.run(detections_batch)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/jupyter-cyril/venv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node efficientnet-b1/model/stem/conv2d/Conv2D (defined at /home/jupyter-cyril/git_projects/automl/efficientdet/backbone/efficientnet_model.py:637) ]]
	 [[strided_slice_10/_1837]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node efficientnet-b1/model/stem/conv2d/Conv2D (defined at /home/jupyter-cyril/git_projects/automl/efficientdet/backbone/efficientnet_model.py:637) ]]
0 successful operations.
0 derived errors ignored.
```

**Comment by mingxingtan** [comment]
Hmm, I don't have this issues on my side. I also just run the command in this [tutorial](https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb) without any problem

I am going to close this issue. If you still have this issue, could you ask this in stackoverflow or tensorflow? Thanks!

**Comment by yongjingli** [comment]
hi, I also meet this problem, my CUDA version is 10.1 and Tensorflow's is '2.1.0' too,  and I think this problem is made by the different version of tensorflow, have you slove the problem? @Cyril9227

**Comment by fuaiguo** [comment]
@Cyril9227 Hi, my CUDA version is 10.1 and Tensorflow's is '2.1.0' , the code is work, but i used the (CUDA version 10.0 and Tensorflow's  '2.0.0') had the same error. have you slove the problem?

**Comment by Xiaokeai18** [comment]
I solved this by change the code in 'inference.py' line 539:    

https://github.com/google/automl/blob/6ecb218626da627ca4c4e4bed4b760c7e66a1b70/efficientdet/inference.py#L539
Replace the line above by the following code:  
```python
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:
```

**Comment by Wenzhao-Xiang** [comment]
@Cyril9227 @yongjingli @fuaiguo  Seems I meet the same issue. I tried tf2.1+cuda10.1 and tf2.0+cuda10.0, but both of them don't work. Finally I changed my python version from 3.7 to 3.6 and the code start to work.

**Comment by drcege** [comment]
@Cyril9227 @yongjingli @fuaiguo @Wenzhao-Xiang 

I think this is caused by mismatched versions of CuDNN. On my side, it says:
```bash
E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN l
ibrary: 7.4.1 but source was compiled with: 7.6.4.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, up
grade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compa
tible with the version specified during compile configuration
```

So, CuDNN of 7.6.4 or higher is needed. If using conda, a simple solution is 
`conda install cudnn=7.6.4`
