### ISSUE TITLE
Training stops on TPU after console disconnects

### ISSUE THREAD

**Issue by InfiniteLife** [google/automl#457]
Im trying to train it on TPU v3-8 but after some time training stops and console freezes. 
No mistakes last output that I see

```
tpu_estimator.py:611] Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
tpu_estimator.py:615] Dequeue next (100) batch(es) of data from outfeed.
transport.py:157] Attempting refresh to obtain initial access_token
INFO:tensorflow:Outfeed finished for iteration (685, 41)
tpu_estimator.py:283] Outfeed finished for iteration (685, 41)
```

I feel like TPU runs out of memory, because I've trained d1 sith batch 64 and it died at 2000 iterations, then I tried batch 32 and it died at 74000 iterations.

Is there a way to fix it or trace the problem?

**Comment by mingxingtan** [comment]
you can try the OOM hook to verify whether it is indeed OOM.

Given this question is vague , I am going to close this issue for now. If you still have this issue or if you find specific issue, feel free to reopen this issue or open a new issue.

**Comment by InfiniteLife** [comment]
> you can try the OOM hook to verify whether it is indeed OOM.
> 
> Given this question is vague , I am going to close this issue for now. If you still have this issue or if you find specific issue, feel free to reopen this issue or open a new issue.

Seems like problem was in Google VM cloud instance through which I connected to TPU. After I switched to my Ubuntu server and connected from it directly to TPU, issue was gone. It was hard to profile because there were literally no errors or messages.
