### ISSUE TITLE
Can this code eval with GPU？

### ISSUE THREAD

**Issue by honghande** [google/automl#60]
// Download coco data.

$ wget http://images.cocodataset.org/zips/val2017.zip

$ wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip

$ unzip val2017.zip

$ unzip annotations_trainval2017.zip

// convert coco data to tfrecord.

$ mkdir tfrecrod

$ PYTHONPATH=".:$PYTHONPATH"  python dataset/create_coco_tfrecord.py \

    --image_dir=val2017 \

    --caption_annotations_file=annotations/captions_val2017.json \

    --output_file_prefix=tfrecord/val \

    --num_shards=32

// Run eval.

$ python main.py --mode=eval  \

    --model_name=${MODEL}  --model_dir=${CKPT_PATH}  \

    --validation_file_pattern=tfrecord/val*  \

    --val_json_file=annotations/instances_val2017.json  \

    --hparams="use_bfloat16=false" --use_tpu=False

but 
NFO:tensorflow:Load EMA vars with ema_decay=0.999800
I0326 16:52:35.189639 140126254118720 det_model_fn.py:533] Load EMA vars with ema_decay=0.999800
INFO:tensorflow:Done calling model_fn.
I0326 16:52:35.490393 140126254118720 estimator.py:1153] Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-03-26T16:52:35Z
I0326 16:52:35.499169 140126254118720 evaluation.py:255] Starting evaluation at 2020-03-26T16:52:35Z
INFO:tensorflow:Graph was finalized.
I0326 16:52:35.855422 140126254118720 monitored_session.py:246] Graph was finalized.
2020-03-26 16:52:35.855795: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-26 16:52:35.878569: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2020-03-26 16:52:35.878996: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x54eabd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-26 16:52:35.879168: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-26 16:52:35.957881: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:35.958395: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x54ae570 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-26 16:52:35.958554: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-03-26 16:52:35.958819: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:35.959207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-03-26 16:52:35.959286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-26 16:52:35.959318: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-26 16:52:35.959393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-26 16:52:35.959419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-26 16:52:35.959443: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-26 16:52:35.959466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-26 16:52:35.959487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-26 16:52:35.959533: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:35.959882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:35.960202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-26 16:52:35.960237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-26 16:52:36.182701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-26 16:52:36.182812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-03-26 16:52:36.182891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-03-26 16:52:36.183086: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:36.183495: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-26 16:52:36.183918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10119 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
INFO:tensorflow:Restoring parameters from /data/internet/AI/automl-master/automl-master/efficientdet/ckpt/efficientdet-d0/model
I0326 16:52:36.185452 140126254118720 saver.py:1284] Restoring parameters from /data/internet/AI/automl-master/automl-master/efficientdet/ckpt/efficientdet-d0/model
INFO:tensorflow:Running local_init_op.
I0326 16:52:37.727182 140126254118720 session_manager.py:504] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0326 16:52:37.800781 140126254118720 session_manager.py:507] Done running local_init_op.
2020-03-26 16:52:40.023219: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-26 16:52:40.023857: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-03-26 16:52:40.024150: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 430.64.0
2020-03-26 16:52:40.024210: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-03-26 16:52:40.024246: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 430.64.0
INFO:tensorflow:evaluation_loop marked as finished
I0326 16:52:40.140067 140126254118720 error_handling.py:108] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0326 16:52:40.140387 140126254118720 error_handling.py:142] Reraising captured error
loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Traceback (most recent call last):
File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node efficientnet-b0/model/stem/conv2d/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node efficientnet-b0/model/stem/conv2d/Conv2D}}]]
	 [[Identity/_4347]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 381, in <module>
    tf.app.run(main)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 311, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3056, in evaluate
    rendezvous.raise_errors()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 143, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3051, in evaluate
    name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 484, in evaluate
    name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 526, in _actual_eval
    return _evaluate()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 515, in _evaluate
    output_dir=self.eval_dir(name))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1622, in _evaluate_run
    config=self._session_config)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node efficientnet-b0/model/stem/conv2d/Conv2D (defined at /data/internet/AI/automl-master/automl-master/efficientdet/backbone/efficientnet_model.py:637) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node efficientnet-b0/model/stem/conv2d/Conv2D (defined at /data/internet/AI/automl-master/automl-master/efficientdet/backbone/efficientnet_model.py:637) ]]
	 [[Identity/_4347]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node efficientnet-b0/model/stem/conv2d/Conv2D:
 IteratorGetNext (defined at /home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/util.py:65)

Input Source operations connected to node efficientnet-b0/model/stem/conv2d/Conv2D:
 IteratorGetNext (defined at /home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/util.py:65)

Original stack trace for 'efficientnet-b0/model/stem/conv2d/Conv2D':
  File "main.py", line 381, in <module>
    tf.app.run(main)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/hjq/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 311, in main
    steps=FLAGS.eval_samples//FLAGS.eval_batch_size)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3051, in evaluate
    name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 484, in evaluate
    name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 526, in _actual_eval
    return _evaluate()
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 508, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1514, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1550, in _call_model_fn_eval
    features, labels, ModeKeys.EVAL, config)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1152, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/data/internet/AI/automl-master/automl-master/efficientdet/det_model_fn.py", line 567, in efficientdet_model_fn
    model=efficientdet_arch.efficientdet)
  File "/data/internet/AI/automl-master/automl-master/efficientdet/det_model_fn.py", line 399, in _model_fn
    cls_outputs, box_outputs = _model_outputs()
  File "/data/internet/AI/automl-master/automl-master/efficientdet/det_model_fn.py", line 389, in _model_outputs
    return model(features, config=hparams_config.Config(params))
  File "/data/internet/AI/automl-master/automl-master/efficientdet/efficientdet_arch.py", line 552, in efficientdet
    features = build_backbone(features, config)
  File "/data/internet/AI/automl-master/automl-master/efficientdet/efficientdet_arch.py", line 328, in build_backbone
    override_params=override_params)
  File "/data/internet/AI/automl-master/automl-master/efficientdet/backbone/efficientnet_builder.py", line 324, in build_model_base
    features = model(images, training=training, features_only=True)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/data/internet/AI/automl-master/automl-master/efficientdet/backbone/efficientnet_model.py", line 637, in call
    outputs = self._relu_fn(
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 209, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1135, in __call__
    return self.conv_op(inp, filter)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 640, in __call__
    return self.call(inp, filter)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 239, in __call__
    name=self.name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2011, in conv2d
    name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 969, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/home/hjq/anaconda3/envs/efficientDet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by mingxingtan** [comment]
Hmm, looks like there are some issues with cudnn for your setting. Are you able to run any other tensorflow code in your environment?

**Comment by honghande** [comment]
Yes, the latest version of tensorflow GPU is installed. It can be run on other projects. It has been installed through import tensorflow as TF

tf.test.is_gpu_available()

Return true to indicate that the GPU is successfully adapted and tensorflow can call the GPU successfully.

**Comment by honghande** [comment]
>>> import tensorflow as tf
2020-03-27 09:07:08.206297: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-27 09:07:08.218659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
>>> tf.test.is_gpu_available()
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-03-27 09:07:44.183665: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-27 09:07:44.206570: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2020-03-27 09:07:44.206939: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3fcd3c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-27 09:07:44.206971: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-27 09:07:44.220867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-27 09:07:44.341337: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.341762: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4059b90 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-27 09:07:44.341775: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-03-27 09:07:44.341870: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.342198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-03-27 09:07:44.342225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-27 09:07:44.342245: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-27 09:07:44.355836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-27 09:07:44.359082: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-27 09:07:44.388301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-27 09:07:44.391012: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-27 09:07:44.391074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-27 09:07:44.391166: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.391612: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.391964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-03-27 09:07:44.391995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-27 09:07:44.750061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-27 09:07:44.750093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-03-27 09:07:44.750099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-03-27 09:07:44.750248: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.750696: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-27 09:07:44.751025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/device:GPU:0 with 10119 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
True

**Comment by wadewangpower** [comment]
Hi，bro， @honghande ,i met the same issue(Failed to get convolution algorithm. This is probably because cuDNN failed to initialize,) just now . and i solved it by switthing to tensorflow1.15.0, this is probably not related to tf version, just because i have different installing way for tf1.15 and tf2.1 before, for tf1.15, i used conda install -n tf1.15 tensorflow-gpu==1.15.0, due to conda will automatically install the corresponding cuda and cudnn, so the issues was gone.

**Comment by qtw1998** [comment]
> Hi，bro， @honghande ,i met the same issue(Failed to get convolution algorithm. This is probably because cuDNN failed to initialize,) just now . and i solved it by switthing to tensorflow1.15.0, this is probably not related to tf version, just because i have different installing way for tf1.15 and tf2.1 before, for tf1.15, i used conda install -n tf1.15 tensorflow-gpu==1.15.0, due to conda will automatically install the corresponding cuda and cudnn, so the issues was gone.
> By the way, i add
> `conf = tf.ConfigProto() conf.gpu_options.allow_growth = True conf.gpu_options.per_process_gpu_memory_fraction = 0.6 session = tf.Session(config=conf)`, i don't sure if it make sense.

HI I met the same bugs! How could I add `conf = tf.ConfigProto() conf.gpu_options.allow_growth = True conf.gpu_options.per_process_gpu_memory_fraction = 0.6 session = tf.Session(config=conf)`
![image](https://user-images.githubusercontent.com/34357479/78175810-0e297f00-748e-11ea-808d-97ed7a31e4b0.png)

**Comment by mingxingtan** [comment]
You might need to install the latest tensorflow. As shown in the [tutorial](https://github.com/google/automl/blob/master/efficientdet/tutorial.ipynb), both train and eval should run well on single GPU, but multi-GPU supports are still on-going.

Closing this issue now, but feel free to add comment to https://github.com/google/automl/issues/29 if you have further questions.

**Comment by erenat77** [comment]
any solution qtw1998 ?
